### ISSUE TITLE
Release 1 roadmap

### ISSUE THREAD

**Issue by jysperm** [jysperm/elecpass#1]
- [x] List and view entries
- [x] Insert entry
- [x] Edit entry
- [x] Delete entry
- [x] Init passstore & set gpg id
- [x] Git init & push & pull
- [x] Build for macOS

**Comment by jysperm** [comment]
<img width="650" alt="elecpass" src="https://user-images.githubusercontent.com/1191561/30779897-a3246b9e-a130-11e7-8cf2-2ac47d007e0f.png">
