### ISSUE TITLE
Release 2 roadmap

### ISSUE THREAD

**Issue by jysperm** [jysperm/elecpass#2]
- [x] Set git remote repo
- [x] A app icon
- [x] Support copy & paste in text input
- [x] Generate password
- [x] Support TOTP field
- [x] Add tests for non-UI code
- [x] Copy to clipboard
- [x] Elecpass Website

**Comment by jysperm** [comment]
<img width="650" alt="elecpass" src="https://user-images.githubusercontent.com/1191561/31860425-7e65605a-b6df-11e7-97d1-adac1f0afdc8.png">
