### ISSUE TITLE
Release 3 roadmap

### ISSUE THREAD

**Issue by jysperm** [jysperm/elecpass#3]
- [x] Move to webpac
- [x] Filter unencrypted content
- [x] Build for Windows
- [x] Rename entry
- [x] Delete field
- [x] Make entries list fit to window

**Comment by namoen0301** [comment]
* HiDPI Support
* Submit to Windows Store (By using Win32 Bridge)

**Comment by jysperm** [comment]
<img width="750" alt="elecpass-v3" src="https://user-images.githubusercontent.com/1191561/48311152-7bf1b400-e5d6-11e8-8044-7d7ada91f78d.png">

**Comment by jysperm** [comment]
v3 was released
