### ISSUE TITLE
Release 4 roadmap

### ISSUE THREAD

**Issue by jysperm** [jysperm/elecpass#5]
- [ ] Realtime feedback (for every button)
- [ ] Fix issues related to rename entry
- [ ] Refactoring pass-strore class, write tests
- [ ] Improve Git commit message
- [ ] Auto Upgrade
- [ ] Getting started guide
- [ ] Improve editing experience
