### ISSUE TITLE
Release 5 roadmap (draft)

### ISSUE THREAD

**Issue by jysperm** [jysperm/elecpass#6]
- [ ] Squash before git push
- [ ] Build for Linux
- [ ] Audit duplicate and weak passwords
- [ ] Watch to file system changes
- [ ] Use CI to run tests
- [ ] Display GPG Id
- [ ] Re-encrypt with GPG Id
- [ ] Display entries as tree view
- [ ] Search encrypted content
